const flights = {
  SA231: [
    { _id: '1A', isAvailable: true },
    { _id: '1B', isAvailable: true },
    { _id: '1C', isAvailable: true },
    { _id: '1D', isAvailable: true },
    { _id: '1E', isAvailable: true },
    { _id: '1F', isAvailable: true },
    { _id: '2A', isAvailable: true },
    { _id: '2B', isAvailable: true },
    { _id: '2C', isAvailable: true },
    { _id: '2D', isAvailable: true },
    { _id: '2E', isAvailable: true },
    { _id: '2F', isAvailable: true },
    { _id: '3A', isAvailable: true },
    { _id: '3B', isAvailable: true },
    { _id: '3C', isAvailable: true },
    { _id: '3D', isAvailable: true },
    { _id: '3E', isAvailable: true },
    { _id: '3F', isAvailable: true },
    { _id: '4A', isAvailable: true },
    { _id: '4B', isAvailable: true },
    { _id: '4C', isAvailable: true },
    { _id: '4D', isAvailable: false },
    { _id: '4E', isAvailable: true },
    { _id: '4F', isAvailable: true },
    { _id: '5A', isAvailable: true },
    { _id: '5B', isAvailable: true },
    { _id: '5C', isAvailable: true },
    { _id: '5D', isAvailable: true },
    { _id: '5E', isAvailable: true },
    { _id: '5F', isAvailable: true },
    { _id: '6A', isAvailable: true },
    { _id: '6B', isAvailable: true },
    { _id: '6C', isAvailable: true },
    { _id: '6D', isAvailable: true },
    { _id: '6E', isAvailable: true },
    { _id: '6F', isAvailable: true },
    { _id: '7A', isAvailable: true },
    { _id: '7B', isAvailable: true },
    { _id: '7C', isAvailable: true },
    { _id: '7D', isAvailable: true },
    { _id: '7E', isAvailable: true },
    { _id: '7F', isAvailable: true },
    { _id: '8A', isAvailable: true },
    { _id: '8B', isAvailable: true },
    { _id: '8C', isAvailable: true },
    { _id: '8D', isAvailable: true },
    { _id: '8E', isAvailable: true },
    { _id: '8F', isAvailable: true },
    { _id: '9A', isAvailable: true },
    { _id: '9B', isAvailable: true },
    { _id: '9C', isAvailable: true },
    { _id: '9D', isAvailable: true },
    { _id: '9E', isAvailable: true },
    { _id: '9F', isAvailable: true },
    { _id: '10A', isAvailable: true },
    { _id: '10B', isAvailable: true },
    { _id: '10C', isAvailable: true },
    { _id: '10D', isAvailable: true },
    { _id: '10E', isAvailable: true },
    { _id: '10F', isAvailable: true },
  ],
};

const reservations = [
  {
    _id: '88a33c23-3332-4ef2-bd71-be7a6430485f',
    flight: 'SA231',
    seat: '4D',
    givenName: 'Marty',
    surname: 'McFly',
    email: 'marty@backfuture.com',
  },
];

module.exports = { flights, reservations };
